# The URL the site will be built for
base_url = "https://bookshelf.rs"

title = "The Rust Bookshelf"
description = "A library of free resources for learning Rust"

compile_sass = true
minify_html = true
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
repo = "https://github.com/miaowware/bookshelf-rs"
